source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'pg', group: [:production]
gem 'redis'
gem 'figaro'

gem 'letter_opener', group: [:development]
gem 'barrister'
gem 'barrister-rails'
gem 'barrister-redis'

gem 'sqlite3', group: [:development, :test]
gem 'pry', group: [:development, :test]

gem 'activerecord'
gem 'foreman'
gem 'puma'
