development:
  adapter: postgresql
  encoding: unicode
  database: basicsoa_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: basicsoa_development
  pool: 5
  username: postgres
